### ISSUE TITLE
Caret inside entity after adding it to the input

### ISSUE THREAD

**Issue by WeshGuillaume** [Backelite/draft-js-autocomplete#3] opened 2019-11-01 17:30 UTC
Hey,

Is it possible to append a space character after the selection with the current implementation ? The problem is that when I select an item from the autocomplete component, the caret stays inside the styled entity component. I already created an [SO question](https://stackoverflow.com/questions/58650389/cursor-inside-entity-after-selection-in-draft-js) .

Do any of you guys have any tips ?

**Comment by bellolau** [comment] 2019-12-11 15:04
Hey,
It's not possible actually.
I close this issue as it's a duplicate of #2

**Closed by bellolau** 2019-12-11 15:04 UTC
Labels: enhancement
